#!/usr/bin/env python3
import sys
from typing import Tuple, List, Set, Dict
from collections import Counter, defaultdict

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, M: int, products: Tuple[int, Set[int]]):
    for i in range(N):
        for j in range(i + 1, N):
            Pi, functionsI = products[i]
            Pj, functionsJ = products[j]

            if Pi > Pj:
                if functionsI <= functionsJ:
                    print(YES)
                    return
            elif Pi < Pj:
                if functionsI >= functionsJ:
                    print(YES)
                    return
            else:
                if functionsI > functionsJ or functionsI < functionsJ:
                    print(YES)
                    return
    print(NO)
    pass


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, M = [int(x) for x in sys.stdin.readline().strip().split()]
    products = []
    for _ in range(N):
        line = [int(x) for x in sys.stdin.readline().strip().split()]
        price = line[0]
        functions = set(line[2:])
        products.append((price, functions))
    solve(N, M, products)
    pass


if __name__ == '__main__':
    main()
