#!/usr/bin/env python3
import sys


def solve(N: int, D: int, S: "List[str]"):
    rows = [list(x) for x in S]
    columns = list(zip(*rows))

    current = 0
    result = 0

    for column in columns:
        if all([x == "o" for x in column]):
            current += 1
            result = max(result, current)
        else:
            current = 0
    print(result)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, D, S)

if __name__ == '__main__':
    main()
