#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(A: int, B: int):
    res = False
    if A == 1 and (B == 2):
        res = True
    elif A == 2 and (B == 1 or B == 3):
        res = True
    elif A == 3 and (B == 2):
        res = True
    elif A == 4 and (B == 5):
        res = True
    elif A == 5 and (B == 4 or B == 6):
        res = True
    elif A == 6 and (B == 5):
        res = True
    elif A == 7 and (B == 8):
        res = True
    elif A == 8 and (B == 7 or B == 9):
        res = True
    elif A == 9 and (B == 8):
        res = True

    print(YES if res else NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)


if __name__ == '__main__':
    main()
