#!/usr/bin/env python3
import sys
from collections import defaultdict


def solve(N: int, S: str):
    counter = defaultdict(int)

    for i, s in enumerate(S):
        counter[s] += 1
        if counter["A"] > 0 and counter["B"] > 0 and counter["C"] > 0:
            print(i+1)
            return
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
