#!/usr/bin/env python3
import sys
from collections import Counter

def solve(S: str):
    counter = Counter(S)
    for k, v in sorted(counter.items(), key=lambda x: x[1]):
        print(S.index(k) + 1)
        break
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
