#!/usr/bin/env python3
import sys


def solve(N: int):
    l = []
    for x in range(N+1):
        for y in range(N+1 - x):
            for z in range(N+1 - x - y):
                l.append((x, y, z))
    
    for x, y, z in sorted(l):
        print("{} {} {}".format(x, y, z))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
