#!/usr/bin/env python3
import sys


def solve(N: int, X: int, S: "List[int]"):
    result = 0

    for s in S:
        if s <= X:
            result += s
    print(result)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    S = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, X, S)

if __name__ == '__main__':
    main()
