#!/usr/bin/env python3
import sys
import heapq
import math


def solve(N: int):
    threathold = int(math.sqrt(N))
    result = float('inf')
    for a in range(1, threathold + 1):
        b = N // a
        if a * b == N:
            result = min(result, a + b - 2)
    print(result)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
