#!/usr/bin/env python3
import sys


def solve(ABCD: str):
    a, b, c, d = list(map(int, ABCD))

    format = ""
    if a + b + c + d == 7:
        format = "{}+{}+{}+{}=7"
    elif a + b + c - d == 7:
        format = "{}+{}+{}-{}=7"
    elif a + b - c + d == 7:
        format = "{}+{}-{}+{}=7"
    elif a + b - c - d == 7:
        format = "{}+{}-{}-{}=7"
    elif a - b + c + d == 7:
        format = "{}-{}+{}+{}=7"
    elif a - b + c - d == 7:
        format = "{}-{}+{}-{}=7"
    elif a - b - c + d == 7:
        format = "{}-{}-{}+{}=7"
    elif a - b - c - d == 7:
        format = "{}-{}-{}-{}=7"

    print(format.format(a, b, c, d))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    ABCD = next(tokens)  # type: str
    solve(ABCD)


if __name__ == '__main__':
    main()
