#!/usr/bin/env python3
import sys


def solve(N: int, M: int, P: int):
    if N < M:
        print(0)
        return
    else:
        rest = N - M
        print(rest // P + 1)
        return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    solve(N, M, P)


if __name__ == '__main__':
    main()
