#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    sorted_list = A[:]
    sorted_list.sort()

    total = sum(sorted_list)
    res = {}
    for num in sorted_list:
        total -= num
        res[num] = total

    ans = []
    for a in A:
        ans.append(res[a])
    print(" ".join([str(x) for x in ans]))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
