#!/usr/bin/env python3
import sys

MOD = 998244353  # type: int


def solve(A: int, B: int, C: int, D: int, E: int, F: int):
    left = (A % MOD) * (B % MOD) * (C % MOD) % MOD
    right = (D % MOD) * (E % MOD) * (F % MOD) % MOD
    result = (left - right) % MOD
    print(result)
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    A, B, C, D, E, F = list(map(int, input().strip().split()))
    solve(A, B, C, D, E, F)

if __name__ == '__main__':
    main()
