#!/usr/bin/env python3
import sys


def solve(S: str):
    n = len(S)

    res = 0
    for i in range(n):
        for j in range(i + 1, n + 1):
            tmp = S[i:j]
            if tmp == "".join(reversed(tmp)):
                res = max(res, len(tmp))
    print(res)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)


if __name__ == '__main__':
    main()
