#!/usr/bin/env python3
import sys


def solve(N: int, X: int, A: "List[int]"):
    A.sort()

    maxValue = sum(A[1:])
    if X > maxValue:
        print(-1)
        return
    if sum(A[:-1]) >= X:
        print(0)
        return

    current = sum(A[1:-1])
    rest = X - current

    if rest > A[-1]:
        print(-1)
        return
    else:
        print(rest)
        return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N - 1)]  # type: "List[int]"
    solve(N, X, A)


if __name__ == '__main__':
    main()
