#!/usr/bin/env python3
import sys
from collections import defaultdict

def solve(N: int, S: str):
    char_count = defaultdict(int)

    left = 0
    right = 0
    while left < N:
        while right < N and S[left] == S[right]:
            right += 1
        
        char_count[S[left]] = max(char_count[S[left]], right - left)
        left = right
    print(sum(char_count.values()))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
