#!/usr/bin/env python3
import sys
from functools import lru_cache

MOD = 1000000007  # type: int


def solve(N: int):
    result = 1

    for i in range(1, N + 1):
        result = (i * result) % MOD

    print(result)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
