#!/usr/bin/env python3
import sys


def solve(Q: int, H: int, S: int, D: int, N: int):
    H = min(H, 2 * Q)
    S = min(S, 2 * H)

    total = 0
    # buy with  S and D
    if 2 * S >= D:
        total += (N // 2) * D
        if N % 2 == 1:
            total += S
    else:
        total += N * S
    print(total)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():

    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    Q = int(next(tokens))  # type: int
    H = int(next(tokens))  # type: int
    S = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    solve(Q, H, S, D, N)


if __name__ == '__main__':
    main()
